const EXTERNAL_TRAVELS = [
  {
    id: 'external-lisboa-2026',
    destiny: 'Lisboa',
    name: 'Lisboa',
    country: 'Portugal',
    hotelCity: 'Lisboa',
    hotelCountry: 'Portugal',
    hotelName: 'Hotel Mirador Atlantico',
    hotelStars: 4,
    startDate: '2026-06-18',
    endDate: '2026-06-23',
    availablePlaces: 18,
    halfBoardPrice: 740,
    fullBoardPrice: 890,
    price: 740,
    rating: 4.7,
    sale: true,
    discountPercentage: 15,
    tag: 'Oferta',
    featured: true,
    description: 'Lisboa te enamora desde el primer tranvía. Pasea por los barrios de Alfama y Belém, prueba los pastéis de nata recién horneados y deja que el fado te lleve a otro tiempo. Una ciudad con luz propia, sabor a mar y una historia que se respira en cada adoquín.',
    imageUrl: 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-praga-2026',
    destiny: 'Praga',
    name: 'Praga',
    country: 'Republica Checa',
    hotelCity: 'Praga',
    hotelCountry: 'Republica Checa',
    hotelName: 'Central Prague Stay',
    hotelStars: 4,
    startDate: '2026-07-04',
    endDate: '2026-07-10',
    availablePlaces: 22,
    halfBoardPrice: 860,
    fullBoardPrice: 1020,
    price: 860,
    rating: 4.8,
    sale: false,
    tag: 'Nuevo',
    featured: true,
    description: 'La ciudad de las cien torres te espera con su casco antiguo medieval intacto, el magnífico Puente de Carlos y una vida nocturna que no para. Praga combina arquitectura gótica y barroca con una escena cultural vibrante. Un destino que supera todas las expectativas.',
    imageUrl: 'https://images.unsplash.com/photo-1564511287568-54483b52a35e?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-sintra-2026',
    destiny: 'Sintra',
    name: 'Sintra',
    country: 'Portugal',
    hotelCity: 'Sintra',
    hotelCountry: 'Portugal',
    hotelName: 'Quinta Verde',
    hotelStars: 3,
    startDate: '2026-08-12',
    endDate: '2026-08-16',
    availablePlaces: 14,
    halfBoardPrice: 620,
    fullBoardPrice: 760,
    price: 620,
    rating: 4.6,
    sale: true,
    discountPercentage: 10,
    tag: 'Escapada',
    featured: false,
    description: 'A tan solo 30 minutos de Lisboa, Sintra parece sacada de un cuento. Sus palacios de colores encaramados entre bosques de pinos y la bruma del Atlántico crean un paisaje de ensueño. El Palácio da Pena y la Quinta da Regaleira son paradas imprescindibles en esta escapada mágica.',
    imageUrl: 'https://images.unsplash.com/photo-1562195168-c82fea0f0953?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-viena-2026',
    destiny: 'Viena',
    name: 'Viena',
    country: 'Austria',
    hotelCity: 'Viena',
    hotelCountry: 'Austria',
    hotelName: 'Ringstrasse Boutique Hotel',
    hotelStars: 4,
    startDate: '2026-09-05',
    endDate: '2026-09-12',
    availablePlaces: 20,
    halfBoardPrice: 980,
    fullBoardPrice: 1180,
    price: 980,
    rating: 4.9,
    sale: false,
    tag: 'Cultural',
    featured: true,
    description: 'Viena es la capital de la cultura europea. Sus museos de clase mundial, la ópera estatal, los cafés vieneses con siglos de historia y el esplendor imperial del Palacio de Schönbrunn hacen de esta ciudad una experiencia única. Mozart, Klimt y Freud caminaron por estas mismas calles.',
    imageUrl: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-dubrovnik-2026',
    destiny: 'Dubrovnik',
    name: 'Dubrovnik',
    country: 'Croacia',
    hotelCity: 'Dubrovnik',
    hotelCountry: 'Croacia',
    hotelName: 'Adriatic View Hotel',
    hotelStars: 4,
    startDate: '2026-10-02',
    endDate: '2026-10-08',
    availablePlaces: 16,
    halfBoardPrice: 920,
    fullBoardPrice: 1090,
    price: 920,
    rating: 4.8,
    sale: true,
    discountPercentage: 12,
    tag: 'Mediterraneo',
    featured: false,
    description: 'La perla del Adriático te recibe con sus murallas medievales que abrazan un casco antiguo declarado Patrimonio de la Humanidad. Aguas de un azul imposible, callejuelas de piedra blanca y atardeceres que tiñen el mar de naranja. Dubrovnik es uno de los destinos más espectaculares del Mediterráneo.',
    imageUrl: 'https://images.unsplash.com/photo-1575540291670-8d3b26f7d327?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-amsterdam-2026',
    destiny: 'Amsterdam',
    name: 'Amsterdam',
    country: 'Paises Bajos',
    hotelCity: 'Amsterdam',
    hotelCountry: 'Paises Bajos',
    hotelName: 'Canal House Boutique',
    hotelStars: 4,
    startDate: '2026-06-28',
    endDate: '2026-07-03',
    availablePlaces: 24,
    halfBoardPrice: 890,
    fullBoardPrice: 1050,
    price: 890,
    rating: 4.7,
    sale: true,
    discountPercentage: 20,
    tag: 'Oferta Flash',
    featured: true,
    description: 'Amsterdam es una ciudad diseñada para vivirla despacio, en bicicleta y a lo largo de sus canales. Los museos Van Gogh y Rijksmuseum, los mercadillos del Jordaan y los tulipanes en el Keukenhof hacen de esta ciudad un destino para repetir. Liberal, cosmopolita y llena de vida.',
    imageUrl: 'https://images.unsplash.com/photo-1459679749680-18eb1eb37418?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-budapest-2026',
    destiny: 'Budapest',
    name: 'Budapest',
    country: 'Hungria',
    hotelCity: 'Budapest',
    hotelCountry: 'Hungria',
    hotelName: 'Danube Palace Hotel',
    hotelStars: 4,
    startDate: '2026-07-18',
    endDate: '2026-07-24',
    availablePlaces: 19,
    halfBoardPrice: 750,
    fullBoardPrice: 910,
    price: 750,
    rating: 4.8,
    sale: false,
    tag: 'Tendencia',
    featured: true,
    description: 'Budapest es el secreto mejor guardado de Europa Central. El Parlamento iluminado sobre el Danubio, los balnearios termales de más de cien años, el barrio judío con sus ruin bars y la gastronomía húngara forman una combinación irresistible. Una ciudad que enamora a primera vista.',
    imageUrl: 'https://images.unsplash.com/photo-1616432902940-b7a1acbc60b3?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-florencia-2026',
    destiny: 'Florencia',
    name: 'Florencia',
    country: 'Italia',
    hotelCity: 'Florencia',
    hotelCountry: 'Italia',
    hotelName: 'Palazzo Toscano',
    hotelStars: 5,
    startDate: '2026-08-22',
    endDate: '2026-08-28',
    availablePlaces: 12,
    halfBoardPrice: 1150,
    fullBoardPrice: 1380,
    price: 1150,
    rating: 4.9,
    sale: true,
    discountPercentage: 18,
    tag: 'Arte y cultura',
    featured: false,
    description: 'La cuna del Renacimiento alberga más obras de arte por metro cuadrado que cualquier otra ciudad del mundo. El David de Miguel Ángel, los Uffizi, el Ponte Vecchio y la cúpula del Brunelleschi son solo el comienzo. Florencia es también una fiesta para el paladar: vino Chianti, bistecca y gelato artesanal.',
    imageUrl: 'https://images.unsplash.com/photo-1476362174823-3a23f4aa6d76?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-santorini-2026',
    destiny: 'Santorini',
    name: 'Santorini',
    country: 'Grecia',
    hotelCity: 'Santorini',
    hotelCountry: 'Grecia',
    hotelName: 'Caldera Blue Suites',
    hotelStars: 5,
    startDate: '2026-09-14',
    endDate: '2026-09-20',
    availablePlaces: 10,
    halfBoardPrice: 1480,
    fullBoardPrice: 1720,
    price: 1480,
    rating: 5.0,
    sale: false,
    tag: 'Lujo',
    featured: true,
    description: 'Santorini es el sueño griego hecho realidad: cúpulas azules sobre acantilados blancos, el mar Egeo extendiéndose hasta el horizonte y los atardeceres más fotografiados del mundo desde Oia. Vinos volcánicos, frutos del mar frescos y una calma única hacen de esta isla una experiencia de lujo incomparable.',
    imageUrl: 'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-estambul-2026',
    destiny: 'Estambul',
    name: 'Estambul',
    country: 'Turquia',
    hotelCity: 'Estambul',
    hotelCountry: 'Turquia',
    hotelName: 'Bosphorus Grand Hotel',
    hotelStars: 4,
    startDate: '2026-10-15',
    endDate: '2026-10-22',
    availablePlaces: 28,
    halfBoardPrice: 820,
    fullBoardPrice: 990,
    price: 820,
    rating: 4.6,
    sale: true,
    discountPercentage: 25,
    tag: 'Mejor precio',
    featured: false,
    description: 'Estambul es el único lugar del mundo donde puedes desayunar en Europa y cenar en Asia. La Mezquita Azul, la Basílica de Santa Sofía, el Gran Bazar y el estrecho del Bósforo conforman un destino que mezcla oriente y occidente de manera única. Un viaje que cambia la perspectiva del mundo.',
    imageUrl: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-edimburgo-2026',
    destiny: 'Edimburgo',
    name: 'Edimburgo',
    country: 'Escocia',
    hotelCity: 'Edimburgo',
    hotelCountry: 'Reino Unido',
    hotelName: 'Royal Mile Inn',
    hotelStars: 3,
    startDate: '2026-07-28',
    endDate: '2026-08-02',
    availablePlaces: 16,
    halfBoardPrice: 690,
    fullBoardPrice: 830,
    price: 690,
    rating: 4.5,
    sale: false,
    tag: 'Aventura',
    featured: false,
    description: 'Edimburgo combina historia medieval con una energía contemporánea inigualable. Su castillo sobre la roca volcánica domina una ciudad llena de festivales, whisky escocés, pubs con música en vivo y el impresionante Arthur\'s Seat desde donde se ve toda la ciudad.',
    imageUrl: 'https://images.unsplash.com/photo-1535448033526-c0e85c9e6968?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-krakow-2026',
    destiny: 'Cracovia',
    name: 'Cracovia',
    country: 'Polonia',
    hotelCity: 'Cracovia',
    hotelCountry: 'Polonia',
    hotelName: 'Old Town Comfort',
    hotelStars: 3,
    startDate: '2026-09-26',
    endDate: '2026-10-01',
    availablePlaces: 20,
    halfBoardPrice: 580,
    fullBoardPrice: 720,
    price: 580,
    rating: 4.6,
    sale: true,
    discountPercentage: 15,
    tag: 'Oferta',
    featured: false,
    description: 'Cracovia es la joya medieval de Polonia y uno de los destinos más asequibles de Europa sin sacrificar ni un ápice de encanto. Su plaza mayor —la más grande de Europa medieval— los restaurantes del barrio judío de Kazimierz y la majestuosa colina del Wawel hacen de esta ciudad una visita imprescindible.',
    imageUrl: 'https://images.unsplash.com/photo-1636903364559-0dfc358abd94?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-niza-2026',
    destiny: 'Niza',
    name: 'Niza',
    country: 'Francia',
    hotelCity: 'Niza',
    hotelCountry: 'Francia',
    hotelName: 'Promenade des Anglais Hotel',
    hotelStars: 4,
    startDate: '2026-08-06',
    endDate: '2026-08-12',
    availablePlaces: 15,
    halfBoardPrice: 1050,
    fullBoardPrice: 1240,
    price: 1050,
    rating: 4.7,
    sale: false,
    tag: 'Costa Azul',
    featured: true,
    description: 'Niza es el corazón de la Costa Azul francesa, donde la elegancia mediterránea se vive a pie de mar. El paseo de los Ingleses, el mercado del Cours Saleya, la cocina niçoise y la cercanía a Mónaco y Cannes hacen de esta ciudad un punto de partida perfecto para explorar la Riviera francesa.',
    imageUrl: 'https://images.unsplash.com/photo-1643914729809-4aa59fdc4c17?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-oslo-2026',
    destiny: 'Oslo',
    name: 'Oslo',
    country: 'Noruega',
    hotelCity: 'Oslo',
    hotelCountry: 'Noruega',
    hotelName: 'Fjord View Hotel',
    hotelStars: 4,
    startDate: '2026-11-06',
    endDate: '2026-11-12',
    availablePlaces: 18,
    halfBoardPrice: 1290,
    fullBoardPrice: 1520,
    price: 1290,
    rating: 4.8,
    sale: true,
    discountPercentage: 10,
    tag: 'Norte de Europa',
    featured: false,
    description: 'Oslo es una ciudad que vive en armonía con la naturaleza. El fiordo de Oslo a un paso del centro, el museo de los barcos vikingos, el parque Vigeland y la ópera flotante sobre el agua forman una ciudad sorprendente. En noviembre aumentan las posibilidades de ver la aurora boreal en los alrededores.',
    imageUrl: 'https://images.unsplash.com/photo-1561794047-33d68ec7f6f6?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
  {
    id: 'external-atenas-2026',
    destiny: 'Atenas',
    name: 'Atenas',
    country: 'Grecia',
    hotelCity: 'Atenas',
    hotelCountry: 'Grecia',
    hotelName: 'Acropolis View Suites',
    hotelStars: 4,
    startDate: '2026-10-25',
    endDate: '2026-10-31',
    availablePlaces: 22,
    halfBoardPrice: 870,
    fullBoardPrice: 1040,
    price: 870,
    rating: 4.7,
    sale: true,
    discountPercentage: 22,
    tag: 'Oferta exclusiva',
    featured: false,
    description: 'Atenas es donde comenzó todo. La Acrópolis con el Partenón, el Ágora antigua, el barrio de Monastiraki con sus mercadillos y la vida en las tabernas del Plaka forman una ciudad que convive con 3.000 años de historia de forma absolutamente natural.',
    imageUrl: 'https://images.unsplash.com/photo-1603565816030-6b389eeb23cb?auto=format&fit=crop&w=800&q=80',
    external: true,
  },
]

export const externalTravelService = {
  getAvailable: async () => EXTERNAL_TRAVELS,
  getFeatured: async () => EXTERNAL_TRAVELS.filter((t) => t.featured === true),
  getOnSale: async () => EXTERNAL_TRAVELS.filter((t) => t.sale === true),
  getById: async (id) => EXTERNAL_TRAVELS.find((t) => String(t.id) === String(id)) ?? null,
}